### ISSUE TITLE
why I use rgba in "border" property cannot work?

### ISSUE THREAD

**Issue by dug-in-sea** [seaneking/postcss-hexrgba#28]
my css shows below:
``` css
  .btn-hover {
    border: 1px solid rbga(#2195F3, 0.8);
    color: rgba(#2196F3, 0.8);
  }
```
in output, the rgba in border cannot be  transformed correctly.
