### ISSUE TITLE
support for custom CSS properties

### ISSUE THREAD

**Issue by hkennyv** [seaneking/postcss-hexrgba#32]
would it be possible to support custom CSS properties with this?

ex:

i've tried this and it doesn't seem to do anything:

```css
:root {
    --accent: #78E2A0;
}

div {
    color: rgba(var(--accent), 0.8);
}
```

but this works:

``` css
:root {
    --accent: #78E2A0;
}

div {
    color: rgba(#78E2A0, 0.8);
}
```
